[build]
  base = "client"
  publish = "client/build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://vetbot-l3wc.onrender.com/api"
  REACT_APP_CHATBOT_TITLE = "Veterinary Assistant"
  REACT_APP_ENVIRONMENT = "production"

[[redirects]]
  from = "/api/*"
  to = "https://vetbot-l3wc.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200